import { _electron as electron, expect } from '@playwright/test'
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import assert from 'node:assert/strict'

const root = await mkdtemp(join(tmpdir(), 'conductor-backlog-'))
const output = resolve('artifacts/backlog')
await mkdir(output, { recursive: true })
const env = { ...process.env, CONDUCTOR_OFFLINE_TESTS: '1', CONDUCTOR_TEST_EMPTY_HISTORY: '1', CONDUCTOR_TEST_MODEL_CATALOG: '1', CONDUCTOR_TEST_NODE_EXECUTABLE: process.execPath, CONDUCTOR_TEST_USER_DATA: join(root, 'profile'), CONDUCTOR_PROJECTS_ROOT: join(root, 'projects') }
delete env.ELECTRON_RUN_AS_NODE
delete env.CONDUCTOR_LIVE_TESTS
const app = await electron.launch({ args: [resolve('out/main/index.js')], env, timeout: 30000 })
const page = await app.firstWindow()
page.setDefaultTimeout(10000)
const errors = [], checks = [], monacoCancellations = []
page.on('pageerror', (error) => {
  const detail = error.stack ?? error.message
  if (error.message === 'Canceled' && /Delayer.cancel/.test(detail) && /WordHighlighter.*dispose/.test(detail)) monacoCancellations.push(detail)
  else errors.push(detail)
})
const shot = async (name) => { await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(resolve, 150))))); const data = await app.evaluate(async ({ BrowserWindow }) => (await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64')); await writeFile(join(output, name + '.png'), Buffer.from(data, 'base64')) }
const check = (name) => { checks.push(name); console.log('PASS ' + name) }
const chooseDialog = async (response) => app.evaluate(({ dialog }, choice) => {
  globalThis.__backlogDialogChoice = choice
  globalThis.__backlogDialogs ??= []
  globalThis.__backlogOriginalDialog ??= dialog.showMessageBox
  dialog.showMessageBox = async (...args) => { const options = args.at(-1); globalThis.__backlogDialogs.push(options); return { response: globalThis.__backlogDialogChoice, checkboxChecked: false } }
}, response)
const activeEditor = () => page.locator('.file-tab-content:not([hidden]) .monaco-editor textarea')
try {
  await page.waitForFunction(() => Boolean(window.conductor?.nativeCli))
  const projects = await page.evaluate(async () => [await window.conductor.projects.create('Backlog Alpha'), await window.conductor.projects.create('Backlog Beta')])
  await writeFile(join(projects[0].path, 'alpha.ts'), 'export const alpha = 1;\n')
  await writeFile(join(projects[0].path, 'context.txt'), 'Context for attachment autocomplete.\n')
  await writeFile(join(projects[1].path, 'beta.html'), '<!doctype html><html><body><h1>Browser file from Beta</h1></body></html>')
  for (let index = 0; index < 35; index++) await writeFile(join(projects[0].path, 'picker-' + String(index).padStart(2, '0') + '.txt'), 'Keyboard navigation fixture')
  await page.reload()
  await page.locator('.project-row').filter({ hasText: 'Backlog Alpha' }).click()
  await page.locator('.launcher-grid button').filter({ hasText: 'Codex' }).click()
  const composer = page.getByRole('textbox', { name: 'Message Codex', exact: true })
  await expect(composer).toBeEnabled()
  const id = await page.locator('.structured-agent-pane').getAttribute('data-structured-session')
  await composer.fill('Unsent draft survives file navigation.')
  await composer.press('Control+e')
  const search = page.getByRole('combobox', { name: 'Search files', exact: true })
  await expect(search).toBeFocused()
  await search.press('ArrowDown')
  const fileOptions = page.locator('.file-picker-results [role=option]')
  await expect(fileOptions.nth(1)).toHaveAttribute('aria-selected', 'true')
  await search.fill('picker-')
  await search.press('ArrowDown')
  await expect(fileOptions.nth(1)).toHaveAttribute('aria-selected', 'true')
  await fileOptions.nth(1).hover()
  for (let index = 0; index < 27; index++) await search.press('ArrowDown')
  await expect(fileOptions.nth(28)).toHaveAttribute('aria-selected', 'true')
  await expect(search).toBeFocused()
  assert.ok(await page.locator('.file-picker-results').evaluate(element => element.scrollTop > 0))
  await search.press('ArrowUp')
  await expect(fileOptions.nth(27)).toHaveAttribute('aria-selected', 'true')
  await search.press('Enter')
  await expect(page.locator('.file-tab.active')).toContainText('picker-27.txt')
  await page.getByRole('button', { name: 'Close picker-27.txt', exact: true }).click()
  check('Ctrl+E immediately accepts arrows, scrolls past the pointer, and opens the keyboard selection')
  await page.keyboard.press('Control+e')
  await expect(fileOptions.first()).toBeVisible()
  const initialCount = await fileOptions.count()
  const initialHeight = await page.locator('.file-picker-results').evaluate(el => el.clientHeight)
  await app.evaluate(({ ipcMain }) => {
    const original = ipcMain._invokeHandlers.get('files:search')
    globalThis.__pickerOriginal = original
    ipcMain.removeHandler('files:search')
    ipcMain.handle('files:search', (...args) => args[2] === 'beta.html' ? new Promise(resolve => { globalThis.__releasePicker = () => resolve(original(...args)) }) : original(...args))
  })
  await search.fill('beta.html')
  await expect.poll(() => app.evaluate(() => typeof globalThis.__releasePicker)).toBe('function')
  await expect(fileOptions).toHaveCount(initialCount)
  assert.equal(await page.locator('.file-picker-results').evaluate(el => el.clientHeight), initialHeight)
  await search.press('Enter')
  await expect(search).toBeVisible()
  await app.evaluate(() => globalThis.__releasePicker())
  await expect(page.locator('.file-tab.active')).toContainText('beta.html')
  await page.getByRole('button', { name: 'Close beta.html', exact: true }).click()
  await app.evaluate(({ ipcMain }) => { ipcMain.removeHandler('files:search'); ipcMain.handle('files:search', globalThis.__pickerOriginal) })
  check('Typing retains the result list and geometry; Enter waits for the current search before opening a file')

  await page.keyboard.press('Control+e')
  await search.fill('beta.html')
  await page.getByRole('option').filter({ hasText: 'beta.html' }).first().click()
  await expect(page.locator('.file-tab')).toContainText('beta.html')
  await expect(page.locator('.project-row.active')).toContainText('Backlog Alpha')
  await expect(composer).toHaveValue('Unsent draft survives file navigation.')
  check('Ctrl+E searches and opens another loaded project without changing the active workspace')
  await page.keyboard.press('Control+e'); await search.fill('alpha.ts')
  await page.getByRole('option').filter({ hasText: 'alpha.ts' }).first().click()
  await expect(page.locator('.file-tab')).toHaveCount(2)
  await expect(activeEditor()).toBeVisible()
  await page.getByRole('button', { name: 'Toggle word wrap', exact: true }).last().click()
  await expect(page.getByRole('button', { name: 'Toggle word wrap', exact: true }).last()).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Toggle word wrap', exact: true }).last().click()
  await activeEditor().focus(); await page.keyboard.press('Control+End'); await page.keyboard.type('export const unsaved = true;')
  await expect(page.locator('.file-tab.active .file-dirty-dot')).toBeVisible()
  await chooseDialog(2)
  await page.getByRole('button', { name: 'Close alpha.ts', exact: true }).click()
  await expect(page.locator('.file-tab.active')).toContainText('alpha.ts')
  assert.equal(await readFile(join(projects[0].path, 'alpha.ts'), 'utf8'), 'export const alpha = 1;\n')
  await chooseDialog(0)
  await page.getByRole('button', { name: 'Close alpha.ts', exact: true }).click()
  await expect(page.locator('.file-tab')).toHaveCount(1)
  assert.match(await readFile(join(projects[0].path, 'alpha.ts'), 'utf8'), /unsaved = true/)
  check('File tabs show dirty state and Cancel/Save preserve exact editor bytes')
  await page.getByRole('button', { name: 'Open in browser', exact: true }).click()
  await expect(page.locator('.file-tab.active [role="tab"]')).toHaveAttribute('title', /Open in browser/)
  await expect(page.locator('.file-tab-content:not([hidden]) webview')).toHaveCount(1)
  await writeFile(join(output, 'geometry.json'), JSON.stringify(await page.evaluate(() => ({ width: innerWidth, height: innerHeight, root: { width: document.getElementById('root').clientWidth, height: document.getElementById('root').clientHeight }, footer: document.querySelector('.statusbar')?.getBoundingClientRect().toJSON(), composer: document.querySelector('.sa-composer')?.getBoundingClientRect().toJSON() })), null, 2))
  await shot('file-browser')
  check('Browser file tab has a visual cue and a sandboxed browser view')
  await page.getByRole('button', { name: 'New file', exact: true }).click()
  await page.getByRole('textbox', { name: 'New file name', exact: true }).fill('created.txt')
  await page.getByRole('textbox', { name: 'New file name', exact: true }).press('Enter')
  await expect(page.locator('.file-tab.active')).toContainText('created.txt')
  assert.equal(await readFile(join(projects[1].path, 'created.txt'), 'utf8'), '')
  check('New file tab creates a file in its owning project')
  await activeEditor().focus(); await page.keyboard.type('Discard this draft')
  await expect(page.locator('.file-tab.active .file-dirty-dot')).toBeVisible()
  await chooseDialog(1)
  await page.getByRole('button', { name: 'Close created.txt', exact: true }).click()
  await expect(page.locator('.file-tab')).toHaveCount(1)
  assert.equal(await readFile(join(projects[1].path, 'created.txt'), 'utf8'), '')
  check("Don't Save discards the editor draft without modifying the file")
  await page.getByRole('button', { name: 'Explorer', exact: true }).click()
  await expect(page.locator('.explorer-project')).toHaveCount(2)
  const betaRoot = page.locator('[data-project-id="' + projects[1].id + '"]')
  await expect(betaRoot).toHaveClass(/root-collapsed/)
  await betaRoot.locator('.explorer-project').click()
  await expect(betaRoot).not.toHaveClass(/root-collapsed/)
  await betaRoot.locator('.explorer-project').click()
  await expect(betaRoot).toHaveClass(/root-collapsed/)
  await betaRoot.locator('.explorer-project').dblclick()
  await expect(betaRoot.getByRole('textbox', { name: 'Rename project' })).toBeFocused()
  await composer.click()
  await expect(betaRoot.getByRole('textbox', { name: 'Rename project' })).toHaveCount(0)
  check('Explorer shows all roots, collapses them, and dismisses inline rename on outside click')
  await page.locator('.quick-theme-toggle').click({ button: 'right' })
  await page.getByRole('menuitemradio', { name: 'Nord' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme-id', 'nord')
  await page.locator('.quick-theme-toggle').click({ button: 'right' })
  await page.locator('.quick-theme-toggle').click({ button: 'right' })
  await expect(page.getByRole('menu', { name: 'Theme' })).toHaveCount(0)
  check('Right-click theme menu selects and toggles closed')
  await page.getByRole('button', { name: 'Attach file context', exact: true }).click()
  const context = page.getByRole('combobox', { name: 'Context file path', exact: true })
  await expect(context).toBeFocused()
  await context.fill('context')
  await page.locator('.sa-file-suggestions').getByRole('option').filter({ hasText: 'context.txt' }).click()
  await expect(page.locator('.sa-context-chips')).toContainText('context.txt')
  await expect(composer).toBeFocused()
  const outline = await composer.evaluate((element) => getComputedStyle(element).outlineStyle)
  assert.equal(outline, 'none')
  check('Attach focuses autocomplete and the composer has no heavy focus outline')
  await page.getByRole('button', { name: 'Conversation history', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Conversation history', exact: true })).toBeVisible()
  await page.mouse.click(8, 70)
  await expect(page.getByRole('dialog', { name: 'Conversation history', exact: true })).toHaveCount(0)
  check('Clicking outside a native modal dismisses it')
  await composer.fill('')
  await expect.poll(async () => (await page.evaluate((id) => window.conductor.structured.snapshot(id), id)).phase).toBe('idle')
  const effort = page.getByRole('slider', { name: 'Reasoning effort' })
  await expect(effort).toBeVisible()
  await effort.fill('1')
  await page.getByRole('combobox', { name: 'Model', exact: true }).click()
  await page.getByRole('option').filter({ hasText: 'No effort model' }).click()
  await expect(effort).toHaveCount(0)
  await expect(page.locator('.sa-effort-unavailable')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Model', exact: true }).click()
  await page.getByRole('option').filter({ hasText: 'Synthetic model' }).click()
  await expect(effort).toHaveAttribute('aria-valuetext', 'Low')
  check('Models without effort hide the control and discard an incompatible prior setting')
  const browserToggle = page.locator('.statusbar').getByRole('button', { name: 'Browser', exact: true })
  await browserToggle.click()
  await expect(page.locator('.browser-sidebar')).toBeVisible()
  await browserToggle.click()
  await expect(page.locator('.browser-sidebar')).toHaveCount(0)
  await browserToggle.click()
  await expect(page.locator('.browser-sidebar')).toBeVisible()
  await page.locator('.activity-rail').getByRole('button', { name: 'Workspace', exact: true }).click()
  check('Browser footer control opens, closes, and reopens the sidebar')
  await page.getByRole('button', { name: 'Automation', exact: true }).click()
  const addAgent = page.getByRole('button', { name: 'Add agent', exact: true })
  await expect(addAgent).toBeVisible()
  assert.deepEqual(await addAgent.evaluate(element => ({ size: getComputedStyle(element).fontSize, transform: getComputedStyle(element).textTransform })), { size: '8px', transform: 'uppercase' })
  await shot('add-agent')
  await page.getByRole('button', { name: 'Close workspace view', exact: true }).click()
  check('Add agent renders in compact uppercase type')
  await page.locator('.activity-rail').getByRole('button', { name: 'Explorer', exact: true }).click()
  const original = await page.evaluate((id) => window.conductor.structured.snapshot(id), id)
  await page.getByRole('button', { name: 'CLI', exact: true }).click()
  await expect(page.locator('.native-cli-terminal')).toBeVisible()
  await expect(page.locator('.native-cli-terminal')).toContainText('Synthetic native CLI')
  await page.getByRole('button', { name: 'Chat', exact: true }).click()
  await expect(composer).toBeVisible()
  const resumed = await page.evaluate((id) => window.conductor.structured.snapshot(id), id)
  assert.equal(resumed.nativeSessionId, original.nativeSessionId)
  assert.equal(resumed.view, 'visual')
  check('CLI switch uses the same native ID and returns to Chat')
  await composer.fill('synthetic:backlog')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('.sa-composer').getByRole('button', { name: 'Stop', exact: true })).toBeVisible()
  await composer.fill('Queued follow-up survives interruption.')
  await page.getByRole('button', { name: 'Queue message', exact: true }).click()
  await expect(page.locator('.sa-queue')).toContainText('Queued follow-up survives interruption.')
  await composer.fill('Second queued message.')
  await page.getByRole('button', { name: 'Queue message', exact: true }).click()
  await composer.fill('Third queued message.')
  await page.getByRole('button', { name: 'Queue message', exact: true }).click()
  await expect(page.locator('.sa-queue')).toHaveCount(3)
  await page.getByRole('button', { name: 'Remove queued message 2', exact: true }).click()
  await expect(composer).toHaveValue('Second queued message.')
  await expect(page.locator('.sa-queue')).toHaveCount(2)
  await composer.fill('')
  await composer.focus(); await page.keyboard.press('Escape')
  await expect(page.locator('.sa-composer').getByRole('button', { name: 'Resume conversation', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Remove queued message 1', exact: true }).click()
  await expect(composer).toHaveValue('Queued follow-up survives interruption.')
  await expect(page.locator('.sa-queue')).toHaveCount(1)
  await composer.fill('')
  await page.getByRole('button', { name: 'Remove queued message 1', exact: true }).click()
  await expect(composer).toHaveValue('Third queued message.')
  await expect(page.locator('.sa-queue')).toHaveCount(0)
  check('Multiple messages queue in order; removing the middle preserves both others; Escape stops and drafts recover intact')
  const bounds = await page.locator('.sa-timeline').evaluate((el) => ({ width: el.clientWidth, scroll: el.scrollWidth }))
  assert.ok(bounds.scroll <= bounds.width + 1, JSON.stringify(bounds))
  check('Long prose and code stay inside the conversation width')
  const link = page.getByRole('link', { name: 'Open alpha', exact: true })
  await link.click(); await expect(activeEditor()).toBeVisible()
  await link.click({ modifiers: ['Control'] })
  await expect(page.locator('.file-tab.active [role=tab]')).toHaveAttribute('title', /Open in browser/)
  await app.evaluate(({ shell }) => { globalThis.__backlogExternal = []; shell.openExternal = async (url) => { globalThis.__backlogExternal.push(url) } })
  await link.click({ modifiers: ['Control', 'Shift'] })
  await expect.poll(() => app.evaluate(() => globalThis.__backlogExternal.length)).toBe(1)
  assert.match(await app.evaluate(() => globalThis.__backlogExternal[0]), /^http:\/\/127\.0\.0\.1:\d+\/[^/]+\/alpha.ts$/)
  const guest = page.locator('.file-tab-content:not([hidden]) webview')
  await expect(guest).toBeVisible()
  const guestId = await guest.evaluate((el) => el.getWebContentsId())
  await app.evaluate(({ webContents }, id) => { const guest = webContents.fromId(id); guest.focus(); guest.sendInputEvent({ type: 'keyDown', keyCode: 'E', modifiers: ['control'] }); guest.sendInputEvent({ type: 'keyUp', keyCode: 'E', modifiers: ['control'] }) }, guestId)
  await expect(search).toBeVisible(); await page.keyboard.press('Escape')
  check('Agent file clicks select editor, embedded browser, or external browser; Ctrl+E works from the browser guest')
  await link.click(); await page.getByRole('button', { name: 'Close alpha.ts', exact: true }).click()

  await page.locator('.activity-rail').getByRole('button', { name: 'Workspace', exact: true }).click()
  const projectRows = page.locator('.project-row-wrap')
  await projectRows.filter({ hasText: 'Backlog Beta' }).dragTo(projectRows.filter({ hasText: 'Backlog Alpha' }), { targetPosition: { x: 10, y: 2 } })
  await expect(page.locator('.project-row').first()).toContainText('Backlog Beta')
  const order = await page.evaluate(() => window.conductor.projects.list())
  assert.equal(order[0].id, projects[1].id)
  check('Project drag ordering persists in the database')
  await page.locator('.sidebar .new-session').click()
  await expect(page.locator('.sidebar-session-row')).toHaveCount(2)
  const sessions = page.locator('.sidebar-session-row')
  await sessions.filter({ hasText: 'Workspace 2' }).dragTo(sessions.filter({ has: page.getByText('Workspace', { exact: true }) }), { targetPosition: { x: 10, y: 2 } })
  const ordered = await page.evaluate((id) => window.conductor.sessions.list(id), projects[0].id)
  assert.equal(ordered[0].name, 'Workspace 2')
  await sessions.filter({ hasText: 'Workspace 2' }).hover()
  await sessions.filter({ hasText: 'Workspace 2' }).getByRole('button', { name: 'Close Workspace 2', exact: true }).click()
  await expect(sessions).toHaveCount(1)
  check('Workspaces can be dragged, persisted, and closed from the sidebar')
  await page.getByRole('button', { name: 'More project actions', exact: true }).click()
  await expect(page.locator('.project-context-menu')).toBeVisible()
  await page.getByRole('button', { name: 'More project actions', exact: true }).click()
  await expect(page.locator('.project-context-menu')).toHaveCount(0)
  await page.getByRole('button', { name: 'Tab actions', exact: true }).click()
  await expect(page.locator('.cursor-context-menu')).toBeVisible()
  await page.getByRole('button', { name: 'Tab actions', exact: true }).click()
  await expect(page.locator('.cursor-context-menu')).toHaveCount(0)
  check('Repeating the project and tab menu triggers closes their dropdowns')
  await page.keyboard.press('Control+e'); await search.fill('alpha.ts')
  await page.getByRole('option').filter({ hasText: 'alpha.ts' }).first().click()
  await expect(activeEditor()).toBeVisible(); await activeEditor().focus()
  await page.keyboard.press('Control+End'); await page.keyboard.type(' // keep on cancel')
  await expect(page.locator('.file-tab.active .file-dirty-dot')).toBeVisible()
  await chooseDialog(2)
  const beforeDialogs = await app.evaluate(() => globalThis.__backlogDialogs.length)
  await page.evaluate(() => window.conductor.window.close())
  await expect.poll(() => app.evaluate(() => globalThis.__backlogDialogs.length)).toBeGreaterThan(beforeDialogs)
  assert.equal(page.isClosed(), false)
  assert.doesNotMatch(await readFile(join(projects[0].path, 'alpha.ts'), 'utf8'), /keep on cancel/)
  check('App close asks about dirty files and Cancel keeps the window and edits open')
  await app.evaluate(({ ipcMain }) => { ipcMain.removeHandler('updates:check'); ipcMain.handle('updates:check', () => ({ phase: 'idle', currentVersion: '0.1.8', configured: true, lastCheckedAt: new Date().toISOString() })) })
  await page.locator('.status-version-button').click()
  await expect(page.locator('.status-version-button')).toContainText('Latest version already installed')
  await expect(page.locator('.status-version-button')).toHaveAttribute('title', /last checked/)
  check('Version number checks for updates and confirms the installed version is current')
  await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0].webContents.send('updates:state', { phase: 'downloading', currentVersion: '0.1.8', availableVersion: '0.1.9', configured: true, source: 'release', progress: 42 }) })
  await expect(page.locator('.statusbar-update')).toContainText('Downloading 42%')
  await expect(page.getByRole('dialog', { name: 'A Conductor update is pending' })).toBeVisible()
  await expect(page.locator('.update-prompt progress')).toHaveAttribute('value', '42')
  await shot('downloading-update')
  await page.keyboard.press('Escape')
  check('Download progress uses a thin progress indicator with readable status')
  await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0].webContents.send('updates:state', { phase: 'ready', currentVersion: '0.1.8', availableVersion: '0.1.9', configured: true, source: 'release' }) })
  if (await page.getByRole('dialog', { name: 'A Conductor update is pending' }).isVisible()) await page.keyboard.press('Escape')
  const restart = page.locator('.statusbar-update.ready')
  await expect(restart).toHaveText('Restart to update')
  await restart.hover()
  const contrast = await restart.evaluate(el => {
    const style = getComputedStyle(el), canvas = document.createElement('canvas')
    canvas.width = canvas.height = 1
    const context = canvas.getContext('2d')
    const luminance = color => {
      context.clearRect(0, 0, 1, 1); context.fillStyle = color; context.fillRect(0, 0, 1, 1)
      const rgb = [...context.getImageData(0, 0, 1, 1).data].slice(0, 3).map(v => v / 255).map(v => v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4)
      return rgb[0] * 0.2126 + rgb[1] * 0.7152 + rgb[2] * 0.0722
    }
    const a = luminance(style.color), b = luminance(style.backgroundColor)
    return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05)
  })
  assert.ok(contrast >= 4.5, 'Restart hover text contrast: ' + contrast)
  await shot('restart-hover')
  check('Restart to update keeps readable contrast when hovered')

  await shot('workspace')
  await chooseDialog(1)
  await page.locator('.sidebar-session-row').hover()
  await page.locator('.sidebar-session-row').getByRole('button', { name: 'Close Workspace', exact: true }).click()
  await expect(page.getByText('No workspace open', { exact: true })).toBeVisible()
  await page.keyboard.press('Control+e'); await search.fill('beta.html')
  await page.getByRole('option').filter({ hasText: 'beta.html' }).first().click()
  await expect(page.locator('.file-tab')).toContainText('beta.html')
  check('Ctrl+E still opens files when every workspace is closed')
  assert.deepEqual(errors, [])
  await writeFile(join(output, 'result.json'), JSON.stringify({ synthetic: true, checks, errors, monacoCancellations }, null, 2) + '\n')
} catch (error) {
  await shot('failure').catch(() => {})
  await writeFile(join(output, 'failure.json'), JSON.stringify({ checks, errors, error: String(error) }, null, 2))
  throw error
} finally { await chooseDialog(1); await app.close() }
